### ISSUE TITLE
"FAT init failed" when running the game

### ISSUE THREAD

**Issue by yejibro** [IAmMoltony/ds-craft#23]
Hello, I've found this project recently and wanted to try it out, but after `make build run` it displays
```
"FAT init failed! :(
This error is probably caused by:
 - ROM is not patched
 - SD card is missing.");
```
I've tried also running the game on a real console and it throws this error too

**Comment by IAmMoltony** [comment]
Hello. If you are using an emulator, please make sure it is set up for DLDI correctly. If you are running it on a real console, then you should patch the ROM file.
This website has instructions on how to patch a ROM: https://www.chishm.com/DLDI/index.html

**Comment by yejibro** [comment]
I have a DSi with TWiLight Menu, nds-bootstrap patches DLDI for me

**Comment by Its-Andy9** [comment]
I patched the rom but it still didn't work
